Vpm:
  {% if is_pool %}
  Roles: ${server_roles} # Only when pool
  {% endif %}
  SkipStages: ${skip_stages}
  {% if is_pool %}
  ClusterUid: ${cluster_uid} # Only when pool
  {% endif %}
  {% if not is_pool %}
  DisableModules: [] # Only when node
  {% endif %}
  ClusterName: ${cluster_name}
  ClusterType: ${cluster_type}
  Token: ${cluster_token}
  InsideNIC: ${public_nic}
  PrivateNIC: ${private_nic}
  PrivateDefaultGw:  ${private_default_gw}
  PrivateVnPrefix: ${private_vn_prefix}
  CustomerRoute: ${customer_route}
  Latitude: ${cluster_latitude}
  Longitude: ${cluster_longitude}
  MauricePrivateEndpoint: ${maurice_mtls_endpoint}
  MauriceEndpoint: ${maurice_endpoint}
  Labels: ${cluster_labels}
  CertifiedHardwareEndpoint: ${certified_hardware_endpoint}
Workload: ${cluster_workload}
Kubernetes:
  CloudProvider: ""
  {% if is_pool %}
  EtcdClusterServers: [] # Only when pool
  {% endif %}
  {% if not is_pool %}
  EtcdUseTLS: True # Only when node
  {% endif %}
  Server: ${service_ip}
  Images:
    Hyperkube: ${image_Hyperkube}
    {% if not is_pool %}
    CoreDNS: ${image_CoreDNS} # Only when node
    Etcd: ${image_Etcd} # Only when node
    {% endif %}